## Import taxi_clean

In [82]:
import warnings
warnings.simplefilter("ignore")

import pandas as pd
import matplotlib as plt
import numpy as np
import time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

#import data 
data = pd.read_csv("taxi_clean_med.csv")

#display data
print(data.shape)
      
data.head()

(8050, 19)

,trip_distance,fare_amount,winter,spring,summer,fall,PULongitude,PULatitude,DOLongitude,DOLatitude,pickup_datetime,dropoff_datetime,ride_duration,Early morning,Morning,Afternoon,Night,Holiday Proximity,label
0,1.1,7.0,0,1,0,0,-73.984176,40.759845,-73.972145,40.756816,2019-04-29 07:55:30,2019-04-29 08:03:39,0 days 00:08:09.000000000,0,1,0,0,0,B
1,2.6,12.0,0,0,1,0,-73.992455,40.748476,-74.008386,40.735248,2019-08-31 14:26:37,2019-08-31 14:42:27,0 days 00:15:50.000000000,0,0,1,0,0,D
2,1.2,5.5,0,0,1,0,-73.965174,40.756589,-73.951208,40.778496,2019-07-07 17:53:54,2019-07-07 17:57:55,0 days 00:04:01.000000000,0,0,1,0,0,B
3,1.9,10.5,0,1,0,0,-73.987973,40.775770,-73.978367,40.764425,2019-04-30 14:45:33,2019-04-30 14:58:43,0 days 00:13:10.000000000,0,0,1,0,0,D
4,1.0,5.5,0,0,0,1,-73.985214,40.727944,-73.976942,40.747654,2019-09-15 01:52:45,2019-09-15 01:57:18,0 days 00:04:33.000000000,1,0,0,0,0,B

In [83]:
data['pickup_datetime'] = pd.to_datetime(data['pickup_datetime'])
data['pickup_datetime'] = pd.to_numeric(data['pickup_datetime'])
data['dropoff_datetime'] = pd.to_datetime(data['dropoff_datetime'])
data['dropoff_datetime'] = pd.to_numeric(data['dropoff_datetime'])

data['ride_duration'] = data['dropoff_datetime'] - data['pickup_datetime']

data.fillna(0, inplace= True)
print (data.dtypes)
data.head()

trip_distance        float64
fare_amount          float64
winter                 int64
spring                 int64
summer                 int64
fall                   int64
PULongitude          float64
PULatitude           float64
DOLongitude          float64
DOLatitude           float64
pickup_datetime        int64
dropoff_datetime       int64
ride_duration          int64
Early morning          int64
Morning                int64
Afternoon              int64
Night                  int64
Holiday Proximity      int64
label                 object
dtype: object

,trip_distance,fare_amount,winter,spring,summer,fall,PULongitude,PULatitude,DOLongitude,DOLatitude,pickup_datetime,dropoff_datetime,ride_duration,Early morning,Morning,Afternoon,Night,Holiday Proximity,label
0,1.1,7.0,0,1,0,0,-73.984176,40.759845,-73.972145,40.756816,1556524530000000000,1556525019000000000,489000000000,0,1,0,0,0,B
1,2.6,12.0,0,0,1,0,-73.992455,40.748476,-74.008386,40.735248,1567261597000000000,1567262547000000000,950000000000,0,0,1,0,0,D
2,1.2,5.5,0,0,1,0,-73.965174,40.756589,-73.951208,40.778496,1562522034000000000,1562522275000000000,241000000000,0,0,1,0,0,B
3,1.9,10.5,0,1,0,0,-73.987973,40.775770,-73.978367,40.764425,1556635533000000000,1556636323000000000,790000000000,0,0,1,0,0,D
4,1.0,5.5,0,0,0,1,-73.985214,40.727944,-73.976942,40.747654,1568512365000000000,1568512638000000000,273000000000,1,0,0,0,0,B

## Base Model (rate x distance) and its RMSE

In [84]:
train, test = train_test_split(data, test_size=0.33, random_state=42)
import numpy as np

rate = data['fare_amount'].mean() / data['trip_distance'].mean()

def compute_rmse(actual, predicted):
  return np.sqrt(np.mean((actual - predicted)**2))

def print_rmse(taxi, rate, name):
  print("RMSE = {}".format(compute_rmse(taxi['fare_amount'], rate * taxi['trip_distance'])), name)
  
print("Rate = ${}/miles".format(rate))
print_rmse(train, rate, 'Train')
print_rmse(test, rate, 'Test')

Rate = $4.325099664913982/miles
RMSE = 6.690599649811109 Train
RMSE = 6.680223799810739 Test

## Random Forest

In [89]:
y = data['label']
X = data.drop(columns=['label'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X, y = make_classification(n_samples=1000, n_features=4, n_informative=2, n_redundant=0,random_state=0, shuffle=False)
random_forest = RandomForestClassifier(n_estimators=200, max_depth=5, max_features= 4, random_state=42)
random_forest.fit(X_train, y_train)

y_pred = random_forest.predict(X_test)

print('\n',confusion_matrix(y_test,y_pred))
print('\n',classification_report(y_test,y_pred))
print('\n',accuracy_score(y_test, y_pred))

 [[163   0   0   0   0   0   0   0   0   0]
 [  0 570   0   0   0   0   0   0   0   0]
 [  0   0 486   0   0   0   0   0   0   0]
 [  0   0   0 342   0   0   0   0   0   0]
 [  0   0   1  46 189   1   0   0   0   0]
 [  0   0   0   9 116  10   0   0   0   0]
 [  0   0   0   6  86  13   1   0   0   0]
 [  0   0   0   2  54   1   1   2   0   5]
 [  0   0   0   0  30   0   0   0   2  29]
 [  0   0   0   0  16   0   0   0   0 234]]

               precision    recall  f1-score   support

           A       1.00      1.00      1.00       163
           B       1.00      1.00      1.00       570
           C       1.00      1.00      1.00       486
           D       0.84      1.00      0.92       342
           E       0.38      0.80      0.52       237
           F       0.40      0.07      0.12       135
           G       0.50      0.01      0.02       106
           H       1.00      0.03      0.06        65
           I       1.00      0.03      0.06        61
           J       0.87      0.94      0.90       250

    accuracy                           0.83      2415
   macro avg       0.80      0.59      0.56      2415
weighted avg       0.85      0.83      0.79      2415


 0.8277432712215321

## Decision Trees

In [48]:
decision_tree = DecisionTreeClassifier(max_depth=5, max_features= 4, random_state=42)
decision_tree.fit(X_train, y_train)
y_pred1 = decision_tree.predict(X_test)

print("Test RMSE: ", mean_squared_error(y_test, y_pred1) ** 0.5)
print('Accuracy Score for Training data',decision_tree.score(X_train,y_train))

ValueError: Expected 2D array, got 1D array instead:
array=[18.  12.5  3.5 ... 35.5 10.5 16.5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.